In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.5.3'

In [4]:
data = pd.read_csv("car_fuel_efficiency.csv")

data

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [6]:
data.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [7]:
data.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [8]:
data[data['origin'] == 'Asia'].groupby('fuel_efficiency_mpg').max()

engine_displacement  num_cylinders  horsepower  \
fuel_efficiency_mpg                                                   
6.886245                             210            6.0        93.0   
6.939508                             290            6.0       145.0   
7.317353                             150            NaN       148.0   
7.329314                             180            3.0       181.0   
7.485553                             240            4.0        92.0   
...                                  ...            ...         ...   
22.858156                            250            6.0       173.0   
22.919968                            110            1.0       183.0   
23.033673                            170           10.0       139.0   
23.204566                            240            2.0         NaN   
23.759123                            330            3.0       136.0   

                     vehicle_weight  acceleration  model_year origin  \
fuel_efficiency_mpg                                                    
6.886245                4345.732510          18.9        2021   Asia   
6.939508                4481.764226          17.4        2010   Asia   
7.317353                4392.759292          17.1        2016   Asia   
7.329314                4661.144932          12.5        2004   Asia   
7.485553                4323.711871          14.8        2007   Asia   
...                             ...           ...         ...    ...   
22.858156               1354.787120          17.3        2007   Asia   
22.919968               1707.231276          11.9        2018   Asia   
23.033673               1491.755825          13.0        2005   Asia   
23.204566               1652.883753          11.0        2018   Asia   
23.759123               1223.298226           NaN        2001   Asia   

                    fuel_type         drivetrain  num_doors  
fuel_efficiency_mpg                                          
6.886245               Diesel    All-wheel drive        0.0  
6.939508             Gasoline    All-wheel drive        0.0  
7.317353               Diesel    All-wheel drive        1.0  
7.329314               Diesel  Front-wheel drive        0.0  
7.485553               Diesel    All-wheel drive       -1.0  
...                       ...                ...        ...  
22.858156            Gasoline  Front-wheel drive        0.0  
22.919968              Diesel    All-wheel drive       -1.0  
23.033673              Diesel  Front-wheel drive        0.0  
23.204566            Gasoline  Front-wheel drive        0.0  
23.759123            Gasoline  Front-wheel drive        1.0  

[3247 rows x 10 columns]

In [9]:
data.horsepower.median()

149.0

In [10]:
data.horsepower.value_counts()

152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
46.0       1
43.0       1
53.0       1
66.0       1
61.0       1
Name: horsepower, Length: 192, dtype: int64

In [11]:
data.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [12]:
data['horsepower'] = data['horsepower'].fillna(152.0)

In [13]:
data.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
data.horsepower.median()

152.0

In [15]:
X = data.loc[data['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7).values

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [16]:
Y = X.T

Y

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [17]:
XTX = Y.dot(X)

XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [18]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [20]:
C = XTX_inv.dot(Y)

C

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [21]:
w = C.dot(y)

w

array([0.01386421, 0.5049067 ])

In [22]:
w.sum()

0.5187709081074016

This is amazing
